server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8844

spring:
  datasource:
    password:
    url: jdbc:MYSQL://localhost:3306/property_management
    username: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:

        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: annewanjikun05@gmail.com
    password: womtbtpmhgyxxzcz

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


security:
  jwt:
    token:
      secret-key: secret-key
      expire-length: 300000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds
      
UserController:
  signin: Authenticates user and returns its JWT token.
  signup: Creates user and returns its JWT token
  delete: Deletes specific user by username
  search: Returns specific user by username
  me: Returns current user's data